### ISSUE TITLE
mpq: add support for wav decompression

### ISSUE THREAD

**Issue by mewmew** [OpenDiablo2/OpenDiablo2#101]
This is just a tracking issue to handle decompression of compressed WAV files.

```
creating: "DATA/GLOBAL/SFX/ambient/creature/rat3.wav"2019/11/07 10:35:00 extracting "DATA\\GLOBAL\\SFX\\ambient\\creature\\rat4.wav"
panic: mpq wav decompression not supported

goroutine 1 [running, locked to thread]:
github.com/OpenDiablo2/OpenDiablo2/mpq.decompressMulti(0xc000e681c0, 0x1a, 0x1a, 0x2c, 0x53ba60, 0xc000090240, 0x0)
	/home/u/goget/pkg/mod/github.com/!open!diablo2/!open!diablo2@v0.0.0-20191107045020-eaeaf5adb968/mpq/MPQStream.go:186 +0x4ae
github.com/OpenDiablo2/OpenDiablo2/mpq.(*Stream).loadBlock(0xc000e16000, 0x2c00000006, 0xc000129000, 0x1000, 0x1000)
	/home/u/goget/pkg/mod/github.com/!open!diablo2/!open!diablo2@v0.0.0-20191107045020-eaeaf5adb968/mpq/MPQStream.go:157 +0x3e4
github.com/OpenDiablo2/OpenDiablo2/mpq.(*Stream).bufferData(0xc000e16000)
	/home/u/goget/pkg/mod/github.com/!open!diablo2/!open!diablo2@v0.0.0-20191107045020-eaeaf5adb968/mpq/MPQStream.go:117 +0x6a
github.com/OpenDiablo2/OpenDiablo2/mpq.(*Stream).readInternal(0xc000e16000, 0xc000176000, 0x602c, 0x602c, 0x602c00006000, 0x1000)
	/home/u/goget/pkg/mod/github.com/!open!diablo2/!open!diablo2@v0.0.0-20191107045020-eaeaf5adb968/mpq/MPQStream.go:100 +0x2f
github.com/OpenDiablo2/OpenDiablo2/mpq.(*Stream).Read(0xc000e16000, 0xc000176000, 0x602c, 0x602c, 0x602c00006000, 0x2600)
	/home/u/goget/pkg/mod/github.com/!open!diablo2/!open!diablo2@v0.0.0-20191107045020-eaeaf5adb968/mpq/MPQStream.go:77 +0xd1
github.com/OpenDiablo2/OpenDiablo2/mpq.MPQ.ReadFile(0xc00001a350, 0xc, 0xc000010040, 0xc00076a000, 0x2000, 0x2600, 0xc0007e2000, 0x93d, 0xa66, 0x201a51504d, ...)
	/home/u/goget/pkg/mod/github.com/!open!diablo2/!open!diablo2@v0.0.0-20191107045020-eaeaf5adb968/mpq/MPQ.go:260 +0x2a2
main.readFile(0xc00008a700, 0xb, 0x11, 0xc000e800c0, 0x29, 0x29, 0x0, 0x0, 0x0, 0x0)
	/home/u/_share_/diablo_ii/foo/a.go:95 +0x27a
main.extractAllFiles(0x7ffdac656948, 0x2, 0x580ee6, 0xc, 0x0, 0x0)
	/home/u/_share_/diablo_ii/foo/a.go:57 +0x571
main.main()
	/home/u/_share_/diablo_ii/foo/a.go:31 +0x1c1
```

To reproduce the above error, simply run the follow Go tool using `go run a.go -l "Diablo II LOD.txt" -mpq_dir /path/to/diablo_2/mpq/archives/`. Where `Diablo II LOD.txt` is the listfile from http://www.zezula.net/download/listfiles.zip and `/path/to/diablo_2/mpq/archives/` is the path to the Diablo II install directory, containing the MPQ archives `d2data.mpq`, `d2sfx.mpq`, etc.

Contents of [a.go](https://play.golang.org/p/lmBhIZRoES8):
```go
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/OpenDiablo2/OpenDiablo2/mpq"
	"github.com/pkg/errors"
)

func main() {
	// Parse command line arguments.
	var (
		// Path to Diablo II MPQ directory.
		mpqDir string
		// path to listfile.txt
		listfilePath string
	)
	flag.StringVar(&mpqDir, "mpq_dir", ".", "path to Diablo II MPQ directory")
	flag.StringVar(&listfilePath, "l", "listfile.txt", "path to listfile")
	flag.Parse()
	// Extract files.
	mpq.InitializeCryptoBuffer()
	if err := extractAllFiles(mpqDir, listfilePath); err != nil {
		log.Fatalf("%+v", err)
	}
}

func extractAllFiles(mpqDir, listfilePath string) error {
	// Open MPQ archives.
	var archives []mpq.MPQ
	mpqNames := []string{"d2char.mpq", "d2video.mpq", "d2data.mpq", "d2xmusic.mpq", "d2exp.mpq", "d2xtalk.mpq", "d2music.mpq", "d2xvideo.mpq", "d2sfx.mpq", "d2speech.mpq", "Patch_D2.mpq"}
	for _, mpqName := range mpqNames {
		mpqPath := filepath.Join(mpqDir, mpqName)
		archive, err := mpq.Load(mpqPath)
		if err != nil {
			return errors.WithStack(err)
		}
		archives = append(archives, archive)
	}
	// Parse listfile.txt
	buf, err := ioutil.ReadFile(listfilePath)
	if err != nil {
		return errors.WithStack(err)
	}
	s := bufio.NewScanner(bytes.NewReader(buf))
	for s.Scan() {
		filePath := s.Text()
		log.Printf("extracting %q\n", filePath)
		data, err := readFile(archives, filePath)
		if err != nil {
			if errors.Cause(err) == ErrNotFound {
				log.Printf("skipping %q", filePath)
				continue
			}
			return errors.WithStack(err)
		}
		filePath = normalize(filePath)
		fmt.Printf("creating: %q", filePath)
		dir := filepath.Dir(filePath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return errors.WithStack(err)
		}
		if err := ioutil.WriteFile(filePath, data, 0644); err != nil {
			return errors.WithStack(err)
		}
	}
	return nil
}

func normalize(filePath string) string {
	filePath = strings.ReplaceAll(filePath, `\`, "/")
	return filePath
}

func readFile(archives []mpq.MPQ, filePath string) ([]byte, error) {
	// de-normalize file name.
	filePath = strings.ToLower(filePath)
	filePath = strings.ReplaceAll(filePath, `/`, "\\")
	if filePath[0] == '\\' {
		filePath = filePath[1:]
	}
	// search for MPQ archive containing file.
	for _, archive := range archives {
		if !archive.FileExists(filePath) {
			continue
		}
		data, err := archive.ReadFile(filePath)
		if err != nil {
			return nil, errors.WithStack(err)
		}
		return data, nil
	}
	return nil, ErrNotFound
}

var ErrNotFound = errors.New("unable to locate MPQ archive")
```

**Comment by mewmew** [comment]
For reference, the following WAV files are compressed:

```
2019/11/07 11:49:13 file read error "DATA\\GLOBAL\\SFX\\ambient\\creature\\rat4.wav"; unable to read file contents
2019/11/07 11:49:14 file read error "data\\global\\sfx\\ambient\\event\\moan7.wav"; unable to read file contents
2019/11/07 11:49:14 file read error "DATA\\GLOBAL\\SFX\\ambient\\footstep\\LightSand1.wav"; unable to read file contents
2019/11/07 11:49:16 file read error "DATA\\GLOBAL\\SFX\\combat\\player\\necromancer\\death3.wav"; unable to read file contents
2019/11/07 11:49:17 file read error "data\\global\\sfx\\monster\\BaalTentacle\\attack1.wav"; unable to read file contents
2019/11/07 11:49:17 file read error "DATA\\GLOBAL\\SFX\\monster\\bloodraven\\deatheffectstart.wav"; unable to read file contents
2019/11/07 11:49:19 file read error "DATA\\GLOBAL\\SFX\\monster\\golemclay\\gethit2.wav"; unable to read file contents
2019/11/07 11:49:20 file read error "data\\global\\sfx\\monster\\Overseer\\death2.wav"; unable to read file contents
2019/11/07 11:49:21 file read error "DATA\\GLOBAL\\SFX\\monster\\scimitar\\attack4.wav"; unable to read file contents
2019/11/07 11:49:23 file read error "DATA\\GLOBAL\\SFX\\monster\\zombie\\raise5.wav"; unable to read file contents
2019/11/07 11:49:24 file read error "DATA\\GLOBAL\\SFX\\object\\ratnest1.wav"; unable to read file contents
2019/11/07 11:49:25 file read error "DATA\\GLOBAL\\SFX\\skill\\barbarian\\leapattack2.wav"; unable to read file contents
2019/11/07 11:49:39 file read error "data\\local\\sfx\\Act1\\Amazon\\Ama_act1_complete_toolsoftrade.wav"; unable to read file contents
2019/11/07 11:49:39 file read error "data\\local\\sfx\\Act1\\Amazon\\Ama_act1_entry_monastery.wav"; unable to read file contents
2019/11/07 11:49:40 file read error "data\\local\\sfx\\Act1\\Barbarian\\Bar_act1_entry_jail.wav"; unable to read file contents
2019/11/07 11:49:41 file read error "data\\local\\sfx\\Act1\\Charsi\\Cha_act1_q1_after_alt.wav"; unable to read file contents
2019/11/07 11:49:51 file read error "data\\local\\sfx\\Act2\\Drognan\\Dro_act2_q6_successful.wav"; unable to read file contents
2019/11/07 11:49:55 file read error "data\\local\\sfx\\Act2\\Jerhyn\\Jer_act2_q4_after.wav"; unable to read file contents
2019/11/07 11:50:03 file read error "data\\local\\sfx\\Act3\\Hratli\\Hra_act3_gossip_08.wav"; unable to read file contents
2019/11/07 11:50:17 file read error "data\\local\\sfx\\Act5\\Necromancer\\Nec_act5_entry_nihlathaksland.wav"; unable to read file contents
2019/11/07 11:50:22 file read error "data\\local\\sfx\\Common\\Sorceress\\Sor_mana.wav"; unable to read file contents
```
