### ISSUE TITLE
Segmentation fault on Arch Linux

### ISSUE THREAD

**Issue by ShadowWarfare** [OpenDiablo2/OpenDiablo2#1119]
I've been trying to run OpenDiablo2 on Arch Linux which I got from AUR via the opendiablo2-git but after transferring all of the game files to the system and then running OpenDiablo2 from command line it gives the following error:
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5572d832962b]

goroutine 1 [running, locked to thread]:
github.com/OpenDiablo2/OpenDiablo2/d2core/d2records.updateEquivalencies(0xc000e60ae0, 0xc000e68e40, 0xc0001d8d80, 0x0, 0x0, 0x0, 0x0)
	github.com/OpenDiablo2/OpenDiablo2/d2core/d2records/item_types_loader.go:128 +0x2b
github.com/OpenDiablo2/OpenDiablo2/d2core/d2records.LoadItemEquivalencies(0xc000e606c0, 0xc000e60ae0, 0xc00002f20f)
	github.com/OpenDiablo2/OpenDiablo2/d2core/d2records/item_types_loader.go:114 +0x445
github.com/OpenDiablo2/OpenDiablo2/d2core/d2records.itemTypesLoader(0xc000088c00, 0xc0004b2400, 0x5572d8652727, 0x20)
	github.com/OpenDiablo2/OpenDiablo2/d2core/d2records/item_types_loader.go:69 +0x1345
github.com/OpenDiablo2/OpenDiablo2/d2core/d2records.(*RecordManager).Load(0xc000088c00, 0x5572d8652727, 0x20, 0xc0004b2400, 0x0, 0x0)
	github.com/OpenDiablo2/OpenDiablo2/d2core/d2records/record_manager.go:300 +0xd6
github.com/OpenDiablo2/OpenDiablo2/d2core/d2asset.(*AssetManager).LoadRecords(0xc000302410, 0x5572d8652727, 0x20, 0x0, 0x0)
	github.com/OpenDiablo2/OpenDiablo2/d2core/d2asset/asset_manager.go:366 +0x85
github.com/OpenDiablo2/OpenDiablo2/d2app.(*App).initDataDictionaries(0xc0000c1540, 0xc000315c00, 0x0)
	github.com/OpenDiablo2/OpenDiablo2/d2app/initialization.go:127 +0xaf
github.com/OpenDiablo2/OpenDiablo2/d2app.(*App).initialize(0xc0000c1540, 0x10, 0xc0003f3f20)
	github.com/OpenDiablo2/OpenDiablo2/d2app/initialization.go:24 +0x73
github.com/OpenDiablo2/OpenDiablo2/d2app.(*App).Run(0xc0000c1540, 0x0, 0x0)
	github.com/OpenDiablo2/OpenDiablo2/d2app/app.go:302 +0x2be
main.main()
	github.com/OpenDiablo2/OpenDiablo2/main.go:22 +0x7e

```
Could be in relation to the previous following bug here: https://github.com/OpenDiablo2/OpenDiablo2/issues/122 

I don't believe it is a hardware or driver issue since I've been having a similar problem and I've tested it on both Laptop and desktop and the error occurs. I don't see any window when trying it.

**Comment by gucio321** [comment]
If I remember, it is related with Diablo 2 patch.
what version of Diablo II do you have installed?
We only support the latest patch (1.14d)

**Comment by ShadowWarfare** [comment]
It was I've installed 1.14d and the game loads, thanks for the help.
