### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gilgamesh3** [OpenDiablo2/OpenDiablo2#122]
**Describe the bug**
->Be me
->Try to run the binary
->After the load of the animations, I get an error
->panic: runtime error: invalid memory address or nil pointer dereference

**To Reproduce**
1. Run the binary
2. Wait
3. See the error

**Logs**

```
2019/11/09 20:48:32.810807 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/main.go:32: OpenDiablo2 - Open source Diablo 2 engine
2019/11/09 20:48:32.833111 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/core/Engine.go:78: Loading configuration file
2019/11/09 20:48:33.048075 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/Palette.go:47: Loaded 18 palettes
2019/11/09 20:48:33.169596 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/TextDictionary.go:35: Loaded 9094 entries from the string table
2019/11/09 20:48:33.170926 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/LevelTypes.go:50: Loaded 38 LevelType records
2019/11/09 20:48:33.185066 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/LevelPresets.go:88: Loaded 1091 level presets
2019/11/09 20:48:33.188981 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/LevelWarp.go:48: Loaded 83 level warps
2019/11/09 20:48:33.197970 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/ObjectTypes.go:30: Loaded 573 object types
2019/11/09 20:48:33.230309 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/Objects.go:352: Loaded 571 objects
2019/11/09 20:48:33.264607 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/Weapons.go:284: Loaded 307 weapons
2019/11/09 20:48:33.280567 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/Armor.go:277: Loaded 203 armors
2019/11/09 20:48:33.294038 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/UniqueItems.go:132: Loaded 352 unique items
2019/11/09 20:48:33.343685 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/Missiles.go:304: Loaded 684 missiles
2019/11/09 20:48:33.433119 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/Sounds.go:102: Loaded 4699 sound definitions
2019/11/09 20:48:33.496098 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/ObjectLookup.go:92: Loaded 7892 object lookups
2019/11/09 20:48:33.564282 $HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/common/AnimationData.go:47: Loaded 3529 animation data records
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x554e7e]

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/internal/glfw.(*Window).ShouldClose(...)
	$HOME/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/glfw/glfw_notwindows.go:206
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update.func1(0xc00041a060, 0x0)
	$HOME/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:757 +0x2e
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Call.func1()
	$HOME/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/thread/thread.go:57 +0x38
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Loop(0xc000092078, 0x96a5c0, 0xc0020dc600)
	$HOME/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/thread/thread.go:43 +0x3b
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run(0xba25e0, 0x320, 0x258, 0x3ff0000000000000, 0xc0004a4020, 0x1a, 0x96a900, 0xc0020dc5c0, 0x96e460, 0xbde6c0, ...)
	$HOME/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:579 +0x20a
github.com/hajimehoshi/ebiten.Run(0x8fd6f0, 0x320, 0x258, 0x3ff0000000000000, 0xc0004a4020, 0x1a, 0x1, 0xc0004a4020)
	$HOME/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/run.go:141 +0x164
main.main()
	$HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/main.go:44 +0x2d9
exit status 2

```

[log.txt](https://github.com/OpenDiablo2/OpenDiablo2/files/3827725/log.txt)

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**
Contents of config.json:

```
{
    "Language": "ENG",
    "FullScreen": false,
    "Scale": 1,
    "TicksPerSecond": -1,
    "RunInBackground": true,
    "VsyncEnabled": true,
    "SfxVolume": 1.0,
    "BgmVolume": 0.3,
    "MpqPath": "/home/gilgamesh/workspace/gamu",
    "MpqLoadOrder": [
        "Patch_D2.mpq",
        "d2exp.mpq",
        "d2xmusic.mpq",
        "d2xtalk.mpq",
        "d2xvideo.mpq",
        "d2data.mpq",
        "d2char.mpq",
        "d2music.mpq",
        "d2sfx.mpq",
        "d2video.mpq",
        "d2speech.mpq"
    ]    
}

```

**Comment by essial** [comment]
We've had a number of people get this error when the engine can't find an MPQ. This should return a helpful error message instead of spewing a stack trace at them.

**Comment by essial** [comment]
My best guess is that this is an issue with ebiten. He has a GMA 3150 (Intel Atom integrated graphics controller), if that helps. I think it's got support for up to OpenGL 2.1.

**Comment by essial** [comment]
hajimehoshi has located the problem and is fixing it. Once he does, I will update go.mod and do a PR. I'll wait for confirmation before closing the ticket.

**Comment by hajimehoshi** [comment]
> hajimehoshi has located the problem and is fixing it

Sorry but my guess was wrong. Now I'm re-investigating the issue.

**Comment by hajimehoshi** [comment]
@gilgamesh3 When this crash happens, did you see any window?

**Comment by essial** [comment]
Can you open go.mod and change this:
`github.com/hajimehoshi/ebiten v1.10.1-0.20191108205544-35436ea50457`
To this:
`github.com/hajimehoshi/ebiten 72c63ece171b87b4203e6f6e2eab42826c56b368`

Then run `go mod tidy` and see if that fixes your issue?

**Comment by essial** [comment]
This is actually a hardware/driver issue. Closing.
