### ISSUE TITLE
Now crash on linux

### ISSUE THREAD

**Issue by liberodark** [OpenDiablo2/OpenDiablo2#145]
**Describe the bug**
With the last commit https://github.com/OpenDiablo2/OpenDiablo2/commit/a6a9434267f858a53bb9b866ff0a42d6b4b23b5f the OpenD2 is crashing.

**To Reproduce**
Just run the executable

**Expected behavior**
```'/home/pc/D2-GO/OpenDiablo2' 
2019/11/12 07:08:21.437857 /home/pc/D2-GO/OpenDiablo2-master/main.go:35: OpenDiablo2 - Open source Diablo 2 engine
2019/11/12 07:08:21.440717 /home/pc/D2-GO/OpenDiablo2-master/d2core/engine.go:92: Loading configuration file
2019/11/12 07:08:21.461131 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/palette.go:49: Loaded 18 palettes
2019/11/12 07:08:21.480458 /home/pc/D2-GO/OpenDiablo2-master/d2common/text_dictionary.go:36: Loaded 9086 entries from the string table
2019/11/12 07:08:21.480636 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/level_types.go:54: Loaded 38 LevelType records
2019/11/12 07:08:21.482377 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/level_presets.go:92: Loaded 1091 level presets
2019/11/12 07:08:21.482931 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/level_warp.go:52: Loaded 83 level warps
2019/11/12 07:08:21.484068 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/object_types.go:34: Loaded 573 object types
2019/11/12 07:08:21.488566 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/objects.go:356: Loaded 571 objects
2019/11/12 07:08:21.491770 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/weapons.go:288: Loaded 307 weapons
2019/11/12 07:08:21.494876 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/armor.go:281: Loaded 203 armors
2019/11/12 07:08:21.497501 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/unique_items.go:136: Loaded 352 unique items
2019/11/12 07:08:21.502448 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/missiles.go:308: Loaded 684 missiles
2019/11/12 07:08:21.512115 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/sounds.go:106: Loaded 4699 sound definitions
2019/11/12 07:08:21.519777 /home/pc/D2-GO/OpenDiablo2-master/d2data/animation_data.go:51: Loaded 3529 animation data records
2019/11/12 07:08:24.617279 /home/pc/D2-GO/OpenDiablo2-master/d2core/game_state.go:125: mkdir /home/pc/.OpenDiablo2/Saves: permission denied
panic: mkdir /home/pc/.OpenDiablo2/Saves: permission denied

goroutine 10 [running]:
log.Panicf(0xc00123c7c0, 0x34, 0x0, 0x0, 0x0)
	/usr/lib/go/src/log/log.go:345 +0xc0
github.com/OpenDiablo2/OpenDiablo2/d2core.getGameBaseSavePath(0xc00844e120, 0xc000a29828)
	/home/pc/D2-GO/OpenDiablo2-master/d2core/game_state.go:125 +0x120
github.com/OpenDiablo2/OpenDiablo2/d2core.HasGameStates(0xe6a080)
	/home/pc/D2-GO/OpenDiablo2-master/d2core/game_state.go:41 +0x22
github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene.(*MainMenu).onSinglePlayerClicked(0xc001e24000)
	/home/pc/D2-GO/OpenDiablo2-master/d2core/d2scene/main_menu.go:207 +0x34
github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene.(*MainMenu).Load.func15.1()
	/home/pc/D2-GO/OpenDiablo2-master/d2core/d2scene/main_menu.go:162 +0x2a
github.com/OpenDiablo2/OpenDiablo2/d2render/d2ui.(*Button).Activate(0xc001e24360)
	/home/pc/D2-GO/OpenDiablo2-master/d2render/d2ui/button.go:180 +0x31
github.com/OpenDiablo2/OpenDiablo2/d2render/d2ui.(*Manager).Update(0xc0007bedd0)
	/home/pc/D2-GO/OpenDiablo2-master/d2render/d2ui/manager.go:129 +0x4d2
github.com/OpenDiablo2/OpenDiablo2/d2core.(*Engine).Update(0xe6a080)
	/home/pc/D2-GO/OpenDiablo2-master/d2core/engine.go:214 +0x205
main.update(0xc001bd4680, 0x0, 0x1)
	/home/pc/D2-GO/OpenDiablo2-master/main.go:54 +0x42
github.com/hajimehoshi/ebiten.(*imageDumper).update(0xc001bd4580, 0xc001bd4680, 0xe87560, 0xc00000f740)
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/imagedumper_desktop.go:105 +0x4e
github.com/hajimehoshi/ebiten.(*uiContext).Update(0xc001bd45c0, 0xc0083ad6a0, 0x0, 0x0)
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/uicontext.go:93 +0x14b
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update(0xb1b780, 0x8da4c0, 0xc001bd45c0, 0x0, 0x0)
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:793 +0x1d6
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).loop(0xb1b780, 0x8da4c0, 0xc001bd45c0, 0x0, 0x0)
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:821 +0x9f
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0xb1b780, 0x320, 0x258, 0x3ff0000000000000, 0xc0008bc000, 0x1a, 0x8da4c0, 0xc001bd45c0, 0xc0006ba120, 0xffffffffffffffff)
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:693 +0x165
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0xc001be8010, 0xc001bea1e0, 0xb1b780, 0x320, 0x258, 0x3ff0000000000000, 0xc0008bc000, 0x1a, 0x8da4c0, 0xc001bd45c0)
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:573 +0x10b
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:570 +0x1c8
```

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version XFCE

**Comment by liberodark** [comment]
I think this PR fix that : https://github.com/OpenDiablo2/OpenDiablo2/pull/144

**Comment by liberodark** [comment]
Ok have try this pr but after create my user have black screen

**Comment by mewmew** [comment]
Black screen means working as intended :)

**Comment by essial** [comment]
Soon guys, soon.
