### ISSUE TITLE
Game crashes on last hero deleting

### ISSUE THREAD

**Issue by averrin** [OpenDiablo2/OpenDiablo2#149]
**Describe the bug**
Game client crashes if I delete the last hero in my saved heroes list

**To Reproduce**
1. Start game
2. Create a hero
3. Restart game
4. Delete saved hero

**Expected behavior**
Idk, but I think the game should return to character selection screen

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**

```
panic: runtime error: index out of range [-1]

goroutine 51 [running]:
github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene.(*CharacterSelect).moveSelectionBox(...)
        /home/averrin/go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene/character_select.go:218
github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene.(*CharacterSelect).refreshGameStates(0xc006556000)
        /home/averrin/go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene/character_select.go:285 +0x2aa
github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene.(*CharacterSelect).onDeleteCharacterConfirmClicked(0xc006556000)
        /home/averrin/go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene/character_select.go:256 +0x75
github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene.(*CharacterSelect).Load.func7.1()
        /home/averrin/go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene/character_select.go:109 +0x2a
github.com/OpenDiablo2/OpenDiablo2/d2render/d2ui.(*Button).Activate(0xc0065565c8)
        /home/averrin/go/src/github.com/OpenDiablo2/OpenDiablo2/d2render/d2ui/button.go:180 +0x31
github.com/OpenDiablo2/OpenDiablo2/d2render/d2ui.(*Manager).Update(0xc0005040d0)
        /home/averrin/go/src/github.com/OpenDiablo2/OpenDiablo2/d2render/d2ui/manager.go:129 +0x4d2
github.com/OpenDiablo2/OpenDiablo2/d2core.(*Engine).Update(0xe6a080)
        /home/averrin/go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/engine.go:214 +0x205
main.update(0xc001462680, 0x4480000000000000, 0x4300000000000000)
        /home/averrin/go/src/github.com/OpenDiablo2/OpenDiablo2/main.go:54 +0x42
github.com/hajimehoshi/ebiten.(*imageDumper).update(0xc001462580, 0xc001462680, 0xe87560, 0xc0011002e0)
        /home/averrin/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/imagedumper_desktop.go:105 +0x4e
github.com/hajimehoshi/ebiten.(*uiContext).Update(0xc0014625c0, 0xc00a937220, 0x0, 0x0)
        /home/averrin/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/uicontext.go:93 +0x14b
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update(0xb1b780, 0x8da4a0, 0xc0014625c0, 0x0, 0x0)
        /home/averrin/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:793 +0x1d6
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).loop(0xb1b780, 0x8da4a0, 0xc0014625c0, 0x0, 0x0)
        /home/averrin/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:821 +0x9f
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0xb1b780, 0x320, 0x258, 0x3ff0000000000000, 0xc000aa0040, 0x1a, 0x8da4a0, 0xc0014625c0, 0xc0005fe000, 0xffffffffffffffff)
        /home/averrin/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:693 +0x165
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0xc000012020, 0xc000078240, 0xb1b780, 0x320, 0x258, 0x3ff0000000000000, 0xc000aa0040, 0x1a, 0x8da4a0, 0xc0014625c0)
        /home/averrin/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:573 +0x10b
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
        /home/averrin/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:570 +0x1c8
```

**Comment by essial** [comment]
This is a known issue. I simply ran out of time last night. Hopefully I’ll have this screen finished tonight!

**Comment by averrin** [comment]
I fixed this by simply
```
diff --git a/d2core/d2scene/character_select.go b/d2core/d2scene/character_select.go
index f3437a2..0374783 100644
--- a/d2core/d2scene/character_select.go
+++ b/d2core/d2scene/character_select.go
@@ -282,6 +282,8 @@ func (v *CharacterSelect) refreshGameStates() {
        }
        v.deleteCharButton.SetEnabled(v.selectedCharacter > -1)
        v.okButton.SetEnabled(v.selectedCharacter > -1)
-       v.moveSelectionBox()
+       if v.selectedCharacter > -1 {
+               v.moveSelectionBox()
+       }
```

But I think this bug doesn't need pull request :)

**Comment by essial** [comment]
Aye the crashes should be fixed tonight when I hopefully finish the screen. It was midnight, I couldn't keep my eyes open 😆

**Comment by essial** [comment]
I fixed this bug, but someone has managed to crash on save file loads so I'm keeping this open until I have more safety nets.

**Comment by liberodark** [comment]
Yes is crash when you close and reopen the game after create player : 

```
./OpenDiablo2
2019/11/13 18:25:16.703137 /home/pc/D2-GO/OpenDiablo2-master/main.go:35: OpenDiablo2 - Open source Diablo 2 engine
2019/11/13 18:25:16.706006 /home/pc/D2-GO/OpenDiablo2-master/d2core/engine.go:92: Loading configuration file
2019/11/13 18:25:16.722898 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/palette.go:49: Loaded 18 palettes
2019/11/13 18:25:16.741841 /home/pc/D2-GO/OpenDiablo2-master/d2common/text_dictionary.go:36: Loaded 9086 entries from the string table
2019/11/13 18:25:16.742004 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/level_types.go:54: Loaded 38 LevelType records
2019/11/13 18:25:16.745229 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/level_presets.go:92: Loaded 1091 level presets
2019/11/13 18:25:16.745492 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/level_warp.go:52: Loaded 83 level warps
2019/11/13 18:25:16.746323 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/object_types.go:34: Loaded 573 object types
2019/11/13 18:25:16.756083 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/objects.go:356: Loaded 571 objects
2019/11/13 18:25:16.759120 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/weapons.go:288: Loaded 307 weapons
2019/11/13 18:25:16.761036 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/armor.go:281: Loaded 203 armors
2019/11/13 18:25:16.763849 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/unique_items.go:136: Loaded 352 unique items
2019/11/13 18:25:16.769258 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/missiles.go:308: Loaded 684 missiles
2019/11/13 18:25:16.786800 /home/pc/D2-GO/OpenDiablo2-master/d2data/d2datadict/sounds.go:106: Loaded 4699 sound definitions
2019/11/13 18:25:16.793541 /home/pc/D2-GO/OpenDiablo2-master/d2data/animation_data.go:51: Loaded 3529 animation data records
2019/11/13 18:25:22.415783 /home/pc/D2-GO/OpenDiablo2-master/d2common/text_dictionary.go:26: Could not find a string for the key 'expansionchar2x'
panic: Could not find a string for the key 'expansionchar2x'

goroutine 8 [running]:
log.Panicf(0x85b55d, 0x28, 0xc0000cd500, 0x1, 0x1)
	/usr/lib/go/src/log/log.go:345 +0xc0
github.com/OpenDiablo2/OpenDiablo2/d2common.TranslateString(...)
	/home/pc/D2-GO/OpenDiablo2-master/d2common/text_dictionary.go:26
github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene.(*CharacterSelect).updateCharacterBoxes(0xc0058dec00)
	/home/pc/D2-GO/OpenDiablo2-master/d2core/d2scene/character_select.go:170 +0x89a
github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene.(*CharacterSelect).refreshGameStates(0xc0058dec00)
	/home/pc/D2-GO/OpenDiablo2-master/d2core/d2scene/character_select.go:294 +0x66
github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene.(*CharacterSelect).Load.func14()
	/home/pc/D2-GO/OpenDiablo2-master/d2core/d2scene/character_select.go:159 +0x66f
github.com/OpenDiablo2/OpenDiablo2/d2core.(*Engine).updateScene(0xe6f080)
	/home/pc/D2-GO/OpenDiablo2-master/d2core/engine.go:154 +0x20e
github.com/OpenDiablo2/OpenDiablo2/d2core.(*Engine).Update(0xe6f080)
	/home/pc/D2-GO/OpenDiablo2-master/d2core/engine.go:199 +0xc7
main.update(0xc000375940, 0x0, 0x0)
	/home/pc/D2-GO/OpenDiablo2-master/main.go:54 +0x42
github.com/hajimehoshi/ebiten.(*imageDumper).update(0xc000375840, 0xc000375940, 0xe8c560, 0xc00000f220)
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/imagedumper_desktop.go:105 +0x4e
github.com/hajimehoshi/ebiten.(*uiContext).Update(0xc000375880, 0xc0081cb080, 0x0, 0x0)
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/uicontext.go:93 +0x14b
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update(0xb20780, 0x8dd180, 0xc000375880, 0x0, 0x0)
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:793 +0x1d6
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).loop(0xb20780, 0x8dd180, 0xc000375880, 0x0, 0x0)
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:821 +0x9f
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0xb20780, 0x320, 0x258, 0x3ff0000000000000, 0xc0005d4000, 0x1a, 0x8dd180, 0xc000375880, 0xc00049e060, 0xffffffffffffffff)
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:693 +0x165
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0xc000012fe0, 0xc0000627e0, 0xb20780, 0x320, 0x258, 0x3ff0000000000000, 0xc0005d4000, 0x1a, 0x8dd180, 0xc000375880)
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:573 +0x10b
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
	/home/pc/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:570 +0x1c8
```

**Comment by essial** [comment]
expansionchar2x can't be found in your copy. Can you dump langdict.txt (it's commented in the source for loading the dictionary files) and find the french version of "EXPANSION CHARACTER" and tell me what that code is?

**Comment by essial** [comment]
Closing due to inactivity.
