### ISSUE TITLE
Panic on startup when loading TreasureClass.txt

### ISSUE THREAD

**Issue by dubonzi** [OpenDiablo2/OpenDiablo2#897]
**Describe the bug**
I'm getting a panic on startup, more especifically when loading data from the `TreasureClass.txt` file. MPQ files are from version 1.14d.

**To Reproduce**
1. run `./build.sh`
2. run `./OpenDiablo2`

**Expected behavior**
Game should start.

**Screenshots**
![image](https://user-images.githubusercontent.com/795838/97874208-6d3ac500-1cf7-11eb-8bd5-234dd2c0e17c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS

**Additional context**
My config.json:
```
{
  "MpqLoadOrder": [
    "Patch_D2.mpq",
    "d2exp.mpq",
    "d2xmusic.mpq",
    "d2xtalk.mpq",
    "d2xvideo.mpq",
    "d2data.mpq",
    "d2char.mpq",
    "d2music.mpq",
    "d2sfx.mpq",
    "d2video.mpq",
    "d2speech.mpq"
  ],
  "Language": "ENG",
  "MpqPath": "/home/eduardo/dev/go/projetos/OpenDiablo2/mpq",
  "TicksPerSecond": -1,
  "FpsCap": 0,
  "SfxVolume": 1,
  "BgmVolume": 0.3,
  "FullScreen": false,
  "RunInBackground": true,
  "VsyncEnabled": true,
  "Backend": "Ebiten"
}
```
Terminal output: 

```
> ./build.sh && ./OpenDiablo2
OpenDiablo 2 Build Script 0.0.8
./build.sh: line 17: pacman: command not found
Check Go
Install libraries
libraries is installed
Build OpenDiablo 2
Build finished. Running OpenDiablo2 will generate a config.json file.
If there are subsequent errors, please inspect and edit the config.json file. See doc/index.html for more details
main.go:20: OpenDiablo2 - Open source Diablo 2 engine
d2config.go:44: loading configuration file from /home/eduardo/.config/OpenDiablo2/config.json...
level_types_loader.go:63: Loaded 36 LevelType records
level_presets_loader.go:47: Loaded 1091 level presets
level_warp_loader.go:35: Loaded 83 level warps
object_types_loader.go:27: Loaded 573 object types
object_details_loader.go:230: Loaded 573 objects
item_weapons_loader.go:18: Loaded 306 weapons
item_armor_loader.go:21: Loaded 202 armors
item_misc_loader.go:18: Loaded 151 misc items
books_loader.go:33: Loaded 3 book items
item_types_loader.go:81: Loaded 99 ItemType records
unique_items_loader.go:133: Loaded 393 unique items
missiles_loader.go:308: Loaded 684 Missile Records
sound_details_loader.go:51: Loaded 4699 sound definitions
monster_stats_loader.go:277: Loaded 733 MonStats records
monster_stats2_loader.go:159: Loaded 609 MonStats2 records
monster_preset_loader.go:26: Loaded 5 MonPreset records
monster_property_loader.go:61: Loaded 13 MonProp records
monster_type_loader.go:28: Loaded 59 MonType records
monster_mode_loader.go:26: Loaded 16 MonMode records
item_affix_loader.go:73: Loaded 253 MagicPrefix records
item_affix_loader.go:73: Loaded 289 MagicSuffix records
itemstatcost_loader.go:100: Loaded 359 ItemStatCost records
item_ratio_loader.go:59: Loaded 6 ItemRatio records
storepage_loader.go:26: Loaded 4 StorePage records
overlays_loader.go:40: Loaded 293 Overlay records
charstats_loader.go:141: Loaded 7 CharStats records
hireling_loader.go:95: Loaded 120 Hireling records
experience_loader.go:73: Loaded 100 Experience Breakpoint records
gems_loader.go:65: Loaded 68 Gems records
item_quality_loader.go:49: Loaded 8 ItemQualities records
runeword_loader.go:93: Loaded 168 records records
difficultylevels_loader.go:39: Loaded 3 DifficultyLevel records
automap_loader.go:42: Loaded 3286 AutoMapRecord records
level_details_loader.go:170: Loaded 137 LevelDetails records
level_maze_loader.go:29: Loaded 81 LevelMazeDetails records
level_substitutions_loader.go:45: Loaded 13 LevelSubstitution records
cubemain_loader.go:86: Loaded 151 CubeMainRecord records
monster_super_unique_loader.go:45: Loaded 66 SuperUnique records
inventory_loader.go:135: Loaded 32 Inventory Panel records
skill_details_loader.go:275: Loaded 357 Skill records
calculations_loader.go:50: Loaded 73 Skill Calculation records
calculations_loader.go:15: Loaded 73 Skill Calculation records
calculations_loader.go:50: Loaded 43 Skill Calculation records
calculations_loader.go:28: Loaded 43 Missile Calculation records
property_loader.go:72: Loaded 268 Property records
skill_description_loader.go:144: Loaded 221 Skill Description records
body_locations_loader.go:24: Loaded 11 Body Location records
set_loader.go:111: Loaded 32 records records
set_item_loader.go:98: Loaded 127 SetItem records
automagic_loader.go:84: Loaded 36 AutoMagic records
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x9c0102]

goroutine 1 [running, locked to thread]:
github.com/OpenDiablo2/OpenDiablo2/d2app.(*App).Run(0xc000170690, 0x0, 0x0)
        /home/eduardo/dev/go/projetos/OpenDiablo2/d2app/app.go:273 +0x262
main.main()
        /home/eduardo/dev/go/projetos/OpenDiablo2/main.go:24 +0x176
```

**Comment by ThomasChr** [comment]
Since when do you get this error? My build is fine and has no such problems. Also I can't remember any changes in this part of the code in the last two weeks.
If it helps, those are my sha1sums:
`b3871164daff4391cf504f2188f36935b68ed3de *D2xMusic.mpq
38a075604834f3320c7476cc73a6a11198bf08d5 *Patch_D2.mpq
a79e7bf17c9afdb3911318607e01419b1e94d7ba *d2char.mpq
7c8bb8938cb2e46762c1469da1fd0b3c39ba86ee *d2data.mpq
dbe301e4bd8e25efc8229b7415e9ad78b3553281 *d2exp.mpq
90ba1a75ee4a2abbe2c3c3d8129db898cbf41ede *d2sfx.mpq
4123cec3fb553812c0772d7fe382828d89a271f4 *d2speech.mpq
51f33040eefbb5a2b3d7fc1885a0799f148418d7 *d2video.mpq
4c0e42dadf2ca88c65bd0f94a82a7bdefb98a5d9 *d2xtalk.mpq
cccc28d0665cbbe143b76dfb2a8df073d4f17e3a *d2xvideo.mpq`

**Comment by gravestench** [comment]
@dubonzi I think your `Patch_D2.mpq` is actually `patch_d2.mpq`.

**Comment by gravestench** [comment]
@dubonzi can you pull latest OD2 source, *delete your config file*, and post your log output? We've recently added some more verbose logging that might illuminate what your issue is.

**Comment by dubonzi** [comment]
Sorry guys, haven't had the time to look into this, I'll update whenever I get the chance.

**Comment by dubonzi** [comment]
> @dubonzi can you pull latest OD2 source, _delete your config file_, and post your log output? We've recently added some more verbose logging that might illuminate what your issue is.

You were right.. I had copied the wrong file over, I got it running now. Sorry about the delay and thanks!
